[metadata]
name = pretix-custom-shop-css-js
version = 1.0.0
description = pretix plugin to inject custom CSS and JS into all organizer presale pages
long_description = file: README.md
long_description_content_type = text/markdown
author = Fraktvred
license = Apache Software License

[options]
packages = find:
include_package_data = True
python_requires = >=3.9
install_requires =
    pretix

[options.entry_points]
pretix.plugin =
    pretix_custom_shop_css_js = pretix_custom_shop_css_js

[tool:pytest]
DJANGO_SETTINGS_MODULE = tests.settings
addopts = --reuse-db
testpaths = tests
pythonpath = .
